spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        file-extension: yaml
        server-addr: 127.0.0.1:8848
    sentinel:
      eager: true
      transport:
        dashboard: 127.0.0.1:8080
  application:
    name: service-order
  config:
    import: nacos:service-order

server:
  port: 8090

feign:
  sentinel:
    enabled: true