spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
    sentinel:
      eager: true
      transport:
        dashboard: 127.0.0.1:8080
  application:
    name: service-product

server:
  port: 8010
feign:
  sentinel:
    enabled: true
